name: wish
description: "A new Flutter project."


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0



  # UI & Icons
  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  hexcolor: ^3.0.1
  flutter_screenutil: ^5.9.0
  flutter_snake_navigationbar: ^0.6.1

  # State Management
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  # Networking
  dio: ^4.0.6

  # Storage & Preferences
  shared_preferences: ^2.0.15

  # Utilities
  device_preview: ^1.1.0
  loader_overlay: ^4.0.1
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.2.4
  url_launcher: ^6.3.1
  device_info_plus:
  dropdown_button2: ^2.3.8
  reorderable_grid: ^1.0.10
  lottie: ^2.2.0
  awesome_dialog: ^3.1.0
  flutter_spinkit: ^5.1.0
  video_player: ^2.7.0
  better_player: ^0.0.83
  chewie:

  # Loading Animations
  loading_animation_widget: ^1.2.0+4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true


  assets:
     - assets/images/
     - assets/animation/
     - assets/lang/


  fonts:
    - family: Almarai
      fonts:
        - asset: assets/fonts/Almarai-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/Almarai-Bold.ttf
          weight: 600
        - asset: assets/fonts/Almarai-Regular.ttf
          weight: 500
        - asset: assets/fonts/Almarai-Light.ttf
          weight: 400
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_Condensed-Black.ttf
          weight: 600
        - asset: assets/fonts/Roboto_Condensed-Regular.ttf
          weight: 600
        - asset: assets/fonts/Roboto_Condensed-Light.ttf
          weight: 500


